%% demo

videos = {'basketball', 'bolt', 'boy', 'car4', 'carDark', 'carScale', ...
	'coke', 'couple', 'crossing', 'david2', 'david3', 'david', 'deer', ...
	'dog1', 'doll', 'dudek', 'faceocc1', 'faceocc2', 'fish', 'fleetface', ...
	'football', 'football1', 'freeman1', 'freeman3', 'freeman4', 'girl', ...
	'ironman', 'jogging-1', 'jogging-2','jumping', 'lemming', 'liquor', 'matrix', ...
	'mhyang', 'motorRolling', 'mountainBike', 'shaking', 'singer1', ...
	'singer2', 'skating1', 'skiing', 'soccer', 'subway', 'suv', 'sylvester', ...
	'tiger1', 'tiger2', 'trellis', 'walking', 'walking2', 'woman'}; %0TB2013

% videos = {'basketball', 'biker', 'bird1', 'BlurBody', 'BlurCar2', 'BlurFace', ...
% 	'BlurOwl', 'Bolt', 'Box', 'Car1', 'Car4', 'CarDark', 'CarScale', ...
% 	'ClifBar', 'Couple', 'Crowds', 'David', 'Deer', 'Diving', 'DragonBaby', ...
% 	'Dudek', 'football', 'Freeman4', 'Girl', 'freeman4', 'Human3', ...
% 	'Human4.2', 'Human6', 'Human9','Ironman', 'Jump', 'Jumping', 'Liquor', ...
% 	'Matrix', 'motorRolling', 'Panda', 'RedTeam', 'Shaking', ...
% 	'Singer2', 'Skating1', 'Skating2.1', 'Skating2.2', 'Skiing', 'Soccer', 'Surfer', 'sylvester', ...
% 	'Tiger2', 'Trellis', 'walking', 'walking2', 'woman'}; %TB-50

all_precisions = zeros(numel(videos),1);  %to compute averages
all_fps = zeros(numel(videos),1);
warning off;
show_visualization = false;
for k = 1:length(videos)
     [all_precisions(k), all_fps(k)] = run_tracker(videos{k}, show_visualization);
end

mean_precision = mean(all_precisions);
fps = mean(all_fps);
fprintf('\nAverage precision (20px):% 1.3f, Average FPS:% 4.2f\n\n', mean_precision, fps);

